[package]
name = "test_rust_voice_streaming"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "voice_test"
path = "test_rust_voice_streaming.rs"

[dependencies]
debabelizer-core = { path = "debabelizer-core" }
debabelizer-soniox = { path = "providers/soniox" }
tokio = { version = "1.40", features = ["full"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }